/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.0 Component Pack 2
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <uart_pc.h>
#include <quaddec_left.h>
#include <encoder_left_sig_a_aliases.h>
#include <encoder_left_sig_a.h>
#include <encoder_left_sig_b_aliases.h>
#include <encoder_left_sig_b.h>
#include <timer_asserv.h>
#include <isr_positionning.h>
#include <quaddec_right.h>
#include <encoder_right_sig_a_aliases.h>
#include <encoder_right_sig_a.h>
#include <encoder_right_sig_b_aliases.h>
#include <encoder_right_sig_b.h>
#include <pwm_right.h>
#include <pwm_left.h>
#include <pwm_right_control_reg.h>
#include <pwm_left_control_reg.h>
#include <mot_right_backward_aliases.h>
#include <mot_right_backward.h>
#include <mot_right_forward_aliases.h>
#include <mot_right_forward.h>
#include <mot_left_backward_aliases.h>
#include <mot_left_backward.h>
#include <mot_left_forward_aliases.h>
#include <mot_left_forward.h>
#include <quaddec_left_isr.h>
#include <quaddec_left_Cnt16.h>
#include <quaddec_right_isr.h>
#include <quaddec_right_Cnt16.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/
